# Generated by Django 5.2.17 on 2026-09-28 22:17

import applications.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(storage=applications.storage.PrivateResumeStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
