# Generated by Django 5.2.17 on 2026-09-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_coremember_unique_core_member_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremember',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coremember',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
