# Generated by Django 5.2.17 on 2026-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='AKATSUKI', max_length=100)),
                ('tagline', models.CharField(default='Build beyond the expected.', max_length=200)),
                ('contact_email', models.EmailField(default='hello@akatsuki.club', max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('footer_text', models.CharField(default='Student technology community. Built by curious minds.', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
