# Generated by Django 5.2.17 on 2026-09-28 23:02

from django.db import migrations, models


def update_existing_contact(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.filter(contact_email__in=['hello@akatsuki.club', '']).update(contact_email='teamakatsukibots@gmail.com')

def reverse_contact_update(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.filter(contact_email='teamakatsukibots@gmail.com').update(contact_email='hello@akatsuki.club')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_existing_contact, reverse_contact_update),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='teamakatsukibots@gmail.com', max_length=254),
        ),
    ]

